import 'package:flutter/material.dart';

/// App-specific copy for the three languages supported by Dini.
class AppLocalizations {
  final Locale locale;

  const AppLocalizations(this.locale);

  static const supportedLocales = <Locale>[
    Locale('tr'),
    Locale('en'),
    Locale('ar'),
  ];

  static AppLocalizations of(BuildContext context) =>
      AppLocalizations(Localizations.localeOf(context));

  String get languageCode =>
      _strings.containsKey(locale.languageCode) ? locale.languageCode : 'tr';

  String text(String key, [Map<String, Object> values = const {}]) {
    var value = _strings[languageCode]?[key] ?? _strings['tr']?[key] ?? key;
    for (final entry in values.entries) {
      value = value.replaceAll('{${entry.key}}', '${entry.value}');
    }
    return value;
  }

  /// Bir dilin tanımlı anahtar kümesi. Üç dil arasındaki pariteyi test eden
  /// `localization_test.dart` tarafından kullanılır.
  @visibleForTesting
  static Set<String> keysFor(String languageCode) =>
      _strings[languageCode]?.keys.toSet() ?? const <String>{};

  String prayer(String name) => text('prayer.$name');

  String month(int month) => text('month.$month');

  static const Map<String, Map<String, String>> _strings = {
    'tr': {
      'appTitle': 'Dini',
      'nav.home': 'Ana Sayfa',
      'nav.quran': 'Kuran',
      'nav.worship': 'İbadet',
      'nav.calendar': 'Takvim',
      'nav.settings': 'Ayarlar',
      'home.greeting': 'Huzurlu bir gün',
      'home.selectedLocation': 'Seçili konum',
      'home.nextPrayer': 'Sıradaki namaz',
      'home.remaining': '{hours} sa {minutes} dk kaldı',
      'home.hijri': 'Hicri {date}',
      'home.friday': 'Cuma',
      'home.ramadan': 'Ramazan',
      'home.qibla': 'Kıble',
      'home.tasbih': 'Tesbih',
      'home.tracker': 'Namaz takibi',
      'home.calendar': 'Takvim',
      'home.todayTimes': 'Bugünün vakitleri',
      'home.now': 'ŞİMDİ',
      'home.next': 'SIRADA',
      'home.sunrise': 'Güneş doğuşu · namaz vakti değildir',
      'home.verse': 'Günün ayeti',
      'home.hadith': 'Günün hadisi',
      'home.prayer': 'Günün duası',
      'settings.title': 'Ayarlar',
      'settings.loadError':
          'Ayarlar yüklenemedi. Güvenli varsayılanlar kullanılabilir.',
      'settings.calculation': 'Hesaplama yöntemi',
      'settings.asrMethod': 'İkindi yöntemi',
      'settings.clock24': '24 saat biçimi',
      'settings.theme': 'Tema',
      'settings.openingTakbir': 'Açılış tekbiri',
      'settings.openingTakbirHint':
          'Uygulama açıldığında çok düşük sesle iki kez “Allahu Ekber” okunur.',
      'settings.language': 'Uygulama dili',
      'settings.languageHint': 'Dil değişikliği anında uygulanır.',
      'settings.hijriNotice': 'Hicri tarih offline tabular hesaplama ile gösterilir; yerel ay gözlemi ve resmi ilanlarla bir gün farklılık gösterebilir.',
      'settings.widgetLocation': 'Widget’ta konum adını göster',
      'settings.widgetLocationHint':
          'Kapalıyken namaz vakitleri gösterilir, şehir adı paylaşılmaz.',
      'settings.widgetLoading': 'Widget gizlilik ayarı yükleniyor…',
      'settings.widgetDefault': 'Widget gizliliği varsayılan olarak kapalı.',
      'settings.notifications': 'Bildirimler',
      'settings.askDiyanet': 'Diyanet’e Soru Sor',
      'settings.about': 'Hakkında ve kaynaklar',
      'settings.premium': 'Premium',
      'settings.privacy': 'Gizlilik Merkezi',
      'language.tr': 'Türkçe',
      'language.en': 'English',
      'language.ar': 'العربية',
      'prayer.fajr': 'Sabah',
      'prayer.sunrise': 'Güneş',
      'prayer.dhuhr': 'Öğle',
      'prayer.asr': 'İkindi',
      'prayer.maghrib': 'Akşam',
      'prayer.isha': 'Yatsı',
      'month.1': 'Ocak',
      'month.2': 'Şubat',
      'month.3': 'Mart',
      'month.4': 'Nisan',
      'month.5': 'Mayıs',
      'month.6': 'Haziran',
      'month.7': 'Temmuz',
      'month.8': 'Ağustos',
      'month.9': 'Eylül',
      'month.10': 'Ekim',
      'month.11': 'Kasım',
      'month.12': 'Aralık',
      'calendar.disclaimer': 'Hicri tarih offline tabular hesaplama ile gösterilir; gözlemlenen tarihler bölgeye ve otoriteye göre değişebilir.',
      'calendar.previousMonth': 'Önceki ay',
      'calendar.nextMonth': 'Sonraki ay',
      'calendar.today': 'Bugün',
      'calendar.religiousDay': 'dini gün',
      'calendar.selectedDay': 'Seçili gün',
      'calendar.noEvent': 'Bu gün için kayıtlı dini etkinlik yok.',
      'calendar.dateNotice': 'Tarihler hesaplanmış İslami takvim tarihidir; yerel ilanlarla farklılık gösterebilir.',
      'weekday.1': 'Pzt',
      'weekday.2': 'Sal',
      'weekday.3': 'Çar',
      'weekday.4': 'Per',
      'weekday.5': 'Cum',
      'weekday.6': 'Cmt',
      'weekday.7': 'Paz',
      'event.ramadan-start': 'Ramazan başlangıcı',
      'event.laylat-al-qadr': 'Kadir Gecesi',
      'event.eid-al-fitr': 'Ramazan Bayramı',
      'event.eid-al-adha': 'Kurban Bayramı',
      'event.mawlid': 'Mevlid Kandili',
      'event.miraj': 'Miraç Kandili',
      'event.berat': 'Berat Kandili',
      'content.removeFavorite': 'Favoriden çıkar',
      'content.addFavorite': 'Favoriye ekle',
      'content.collapse': 'Daralt',
      'content.more': 'Devamını gör',
      'content.copy': 'Metni kopyala',
      'content.copied': 'Metin kopyalandı',
      'content.share': 'Paylaş',
      'tasbih.select': 'Zikir seçimi',
      'tasbih.target': 'Hedef',
      'tasbih.decrease': 'Bir azalt',
      'tasbih.increase': 'Bir artır',
      'tasbih.reset': 'Sıfırla',
      'tasbih.haptic': 'Hafif dokunsal geri bildirim',
      'tasbih.history': 'Son oturumlar',
      'dhikr.subhanallah': 'Sübhanallah',
      'dhikr.alhamdulillah': 'Elhamdülillah',
      'dhikr.allahu-akbar': 'Allahu Ekber',
      'dhikr.salawat': 'Salavat',
      'qibla.sensorUnavailable': 'Pusula sensörü kullanılamıyor. Telefonu düz tutup kalibrasyon hareketini deneyin.',
      'qibla.title': 'Telefonun üstünü Kâbe yönüne çevirin',
      'qibla.ready': 'Kıble yönündesiniz',
      'qibla.turnRight': 'Sağa {degrees}° dönün',
      'qibla.turnLeft': 'Sola {degrees}° dönün',
      'qibla.bearings': 'Cihaz {heading}° · Kıble {qibla}°',
      'qibla.calibration': 'Pusulayı kalibre edin',
      'qibla.calibrationHint': 'Telefonu düz tutun ve havada birkaç kez 8 çizin. Metal eşyalardan uzaklaşın.',
      'qibla.heading': 'Cihaz yönü: {degrees}°{aligned}',
      'qibla.aligned': ' · Hizalı',
      'qibla.privacy': 'Konum cihazda tutulur; dışarı gönderilmez.',
      'tracker.title': 'Namaz Takibi',
      'tracker.today': 'Bugünün namazları',
      'tracker.completed': '{completed} / {total} tamamlandı',
      'tracker.privacy': 'Takip verileri seçili günün yerel tarihine göre yalnızca cihazda saklanır.',
      'worship.title': 'İbadet Rehberi',
      'worship.tracker': 'Takip',
      'worship.prayerGuide': 'Namaz nasıl kılınır?',
      'worship.tabPrayer': 'Namaz',
      'worship.tabWudu': 'Abdest',
      'worship.wudu': 'Abdest nasıl alınır?',
      'worship.alarms': 'Alarmlar',
      'guide.prayerTitle': 'Beş vakit namaz rehberi',
      'guide.prayerIntro': 'Namazı seçerek sünnet, farz ve vitir sırasını; temel hareketleri görsellerle adım adım inceleyin.',
      'guide.schoolNotice': 'Mezheplere göre bazı ayrıntılar değişebilir. Rekât sıralaması Diyanet’in yaygın Hanefî anlatımını temel alır.',
      'guide.rakat': 'rekât',
      'guide.rakatCount': '{count} rekât',
      'guide.firstSunnah': 'İlk sünnet',
      'guide.fard': 'Farz',
      'guide.finalSunnah': 'Son sünnet',
      'guide.witr': 'Vitir vacip',
      'guide.orderTitle': 'Kılınış sırası',
      'guide.movementsTitle': 'Bir rekâtın temel akışı',
      'guide.prayerImageLabel':
          'Namaz hareketlerini gösteren sekiz aşamalı görsel rehber',
      'guide.prayerStep1':
          'Niyet edin, kıbleye dönün ve başlangıç tekbiriyle namaza durun.',
      'guide.prayerStep2':
          'Kıyamda elleri bağlayın; Fâtiha ve uygun sûre veya âyetleri okuyun.',
      'guide.prayerStep3': '“Allahu Ekber” diyerek rükûya eğilin; sırtı düz tutup elleri dizlere koyun.',
      'guide.prayerStep4': 'Rükûdan doğrulup kısa süre ayakta durun.',
      'guide.prayerStep5': 'Tekbirle secdeye gidin; alın ve burunla birlikte eller, dizler ve ayak parmakları yere gelsin.',
      'guide.prayerStep6':
          'Secdeden doğrulup iki secde arasında kısa süre oturun.',
      'guide.prayerStep7':
          'İkinci secdeyi yapın; sonraki rekât varsa ayağa kalkın.',
      'guide.prayerStep8': 'Son oturuşta Tahiyyat, salavat ve duaları okuyup iki yana selâm verin.',
      'guide.rakatLabel': '{index}. rekât',
      'guide.finalSitting': 'Son oturuş',
      'guide.recitationsTitle': 'Okunacak metinler',
      'guide.recitationsEmpty': 'Bu bölüm için Arapça metin, okunuş ve anlam henüz eklenmedi. İçerik doğrulanmış bir kaynaktan eklenecektir.',
      'guide.transliteration': 'Okunuş',
      'guide.meaning': 'Anlam',
      'recitation.subhaneke.name': 'Sübhâneke',
      'recitation.fatiha.name': 'Fâtiha sûresi',
      'recitation.ettehiyyatu.name': 'Ettehiyyâtü',
      'recitation.allahummeSalli.name': 'Allâhümme salli',
      'recitation.allahummeBarik.name': 'Allâhümme bârik',
      'recitation.rabbenaAtina.name': 'Rabbenâ âtinâ',
      'recitation.rabbenagfirli.name': 'Rabbenâğfirlî',
      'recitation.kunut.name': 'Kunut duaları',
      'recitation.subhaneke.meaning': 'Allah’ım! Seni bütün eksikliklerden tenzih eder, sana hamd ederim. Senin adın mübarektir, şânın yücedir; senden başka ilah yoktur.',
      'recitation.fatiha.meaning': 'Rahmân ve Rahîm olan Allah’ın adıyla. Hamd, âlemlerin Rabbi Allah’a mahsustur. O Rahmân’dır, Rahîm’dir. Hesap gününün sahibidir. Yalnız sana kulluk eder, yalnız senden yardım dileriz. Bizi doğru yola ilet; nimet verdiklerinin yoluna, gazaba uğrayanların ve sapanların yoluna değil.',
      'recitation.ettehiyyatu.meaning': 'Dil, beden ve mal ile yapılan bütün ibadetler Allah’a mahsustur. Ey Peygamber! Allah’ın selâmı, rahmeti ve bereketi senin üzerine olsun. Selâm bizim ve Allah’ın iyi kullarının üzerine olsun. Şahitlik ederim ki Allah’tan başka ilah yoktur; yine şahitlik ederim ki Muhammed O’nun kulu ve elçisidir.',
      'recitation.allahummeSalli.meaning': 'Allah’ım! İbrâhim’e ve İbrâhim’in ailesine rahmet ettiğin gibi Muhammed’e ve Muhammed’in ailesine de rahmet et. Şüphesiz sen övülmeye lâyıksın, şân ve şeref sahibisin.',
      'recitation.allahummeBarik.meaning': 'Allah’ım! İbrâhim’i ve ailesini mübarek kıldığın gibi Muhammed’i ve ailesini de mübarek kıl. Şüphesiz sen övülmeye lâyıksın, şân ve şeref sahibisin.',
      'recitation.rabbenaAtina.meaning': 'Rabbimiz! Bize dünyada da iyilik ver, âhirette de iyilik ver ve bizi ateş azabından koru.',
      'recitation.rabbenagfirli.meaning': 'Rabbimiz! Hesabın görüleceği gün beni, anne babamı ve bütün müminleri bağışla.',
      'recitation.kunut.meaning': 'Allah’ım! Senden yardım, bağışlanma ve doğru yola iletmeni isteriz. Sana inanır, sana tövbe eder, sana güveniriz. Bütün hayrı sana nispet ederek seni överiz. Sana şükreder, nankörlük etmeyiz. Sana karşı gelenlerden uzaklaşır, onları terk ederiz. — Allah’ım! Yalnız sana kulluk eder, yalnız senin için namaz kılar ve secde ederiz. Sana koşar, senin rızanı ararız. Rahmetini umar, azabından korkarız; şüphesiz senin azabın inkâr edenlere ulaşacaktır.',
      'recitation.source.ilmihal':
          'Kaynak: Diyanet İşleri Başkanlığı, Namaz İlmihali.',
      'recitation.source.fatiha': 'Kaynak: Kur’an-ı Kerim, Fâtiha sûresi 1-7.',
      'recitation.source.bakara201':
          'Kaynak: Kur’an-ı Kerim, Bakara sûresi 201.',
      'recitation.source.ibrahim41':
          'Kaynak: Kur’an-ı Kerim, İbrâhim sûresi 41.',
      'guide.beginnerTitle': 'Başlamadan önce',
      'guide.beginnerEssentials': 'Namaz vaktinin girmiş olması, abdest, temiz kıyafet ve yer, örtünme, kıble ve niyet temel hazırlıklardır.',
      'guide.wuduIntro': 'Niyet edip besmele çekin. Suyu israf etmeden aşağıdaki sırayı uygulayın.',
      'guide.wuduImageLabel': 'Abdestin sekiz aşamasını gösteren görsel rehber',
      'guide.wuduStep1':
          'Ellerinizi bileklerle ve parmak aralarıyla birlikte üç kez yıkayın.',
      'guide.wuduStep2': 'Sağ elinizle ağzınıza üç kez su verip çalkalayın.',
      'guide.wuduStep3': 'Burnunuza üç kez nazikçe su verip temizleyin.',
      'guide.wuduStep4': 'Yüzünüzün tamamını üç kez yıkayın.',
      'guide.wuduStep5':
          'Önce sağ, sonra sol kolu dirseklerle birlikte üç kez yıkayın.',
      'guide.wuduStep6': 'Islak ellerle başın bir bölümünü bir kez mesh edin.',
      'guide.wuduStep7': 'Kulakları, ardından enseyi ıslak ellerle mesh edin.',
      'guide.wuduStep8': 'Önce sağ, sonra sol ayağı topuklar ve parmak aralarıyla birlikte üç kez yıkayın.',
      'guide.source': 'Kaynak: Diyanet İşleri Başkanlığı, Namaz İlmihali ve Din İşleri Yüksek Kurulu.',
      'premium.freeTitle': 'Temel ibadet özellikleri ücretsizdir.',
      'premium.freeFeatures': 'Ücretsiz: namaz vakitleri, kıble, temel bildirimler, Hicri takvim, günlük içerik, temel takip, tesbih, temel widget ve varsayılan cami sahnesi.',
      'premium.features': 'Premium: ek sahne ve widget görünümleri, görünüm kişiselleştirme ve yerel gelişmiş istatistikler.',
      'premium.loading': 'Mağaza ürünleri yükleniyor…',
      'premium.unavailable': 'Mağaza ürünleri şu anda kullanılamıyor. Fiyat gösterilmedi. Ücretsiz özellikler kullanılmaya devam eder.',
      'premium.launchTitle': 'Şu anda her şey ücretsiz',
      'premium.launchBody': 'Uygulama lansman döneminde tam sürüm olarak sunuluyor; bütün özellikler açık ve herhangi bir satın alma gerekmiyor. Abonelik ileride açılabilir, o zamana kadar ödeme alınmaz.',
      'quran.comingSoonTitle': 'Kuran ekranı yakında',
      'quran.comingSoonBody': 'Kuran bölümü hazırlanıyor. Metin, güvenilir ve kullanım izni açık bir kaynaktan eklenecek; hazır olmadan uygulamaya konmayacak.',
      'quran.comingSoonNote': 'O zamana kadar namaz vakitleri, kıble, ibadet rehberi ve takvim bölümlerini kullanabilirsiniz.',
      'premium.restore': 'Satın alımları geri yükle',
      'premium.restoreSent': 'Geri yükleme isteği mağazaya gönderildi.',
      'premium.active': 'Premium etkin',
      'premium.cache':
          'Mağaza durumu yerel kullanıcı deneyimi önbelleğiyle gösteriliyor.',
      'notifications.description': 'Namaz vakitlerini cihazınızda hesaplayarak size yerel bildirim gönderebiliriz.',
      'notifications.sound': 'Bildirim sesi',
      'notifications.defaultSound': 'Varsayılan',
      'notifications.bundledSound': 'Uygulama tonu',
      'notifications.silent': 'Sessiz',
      'notifications.friday': 'Cuma hatırlatıcısı',
      'notifications.suhoor': 'Ramazan sahur/sabah yaklaşma',
      'notifications.iftar': 'Ramazan iftar/akşam yaklaşma',
      'notifications.permissionDone': 'İzin durumu işlendi',
      'notifications.managePermission': 'Bildirim izinlerini yönet',
      'notifications.notice': 'Bildirimler yerel olarak planlanır. Tam uzunlukta ezan sesinin arka planda her platformda garanti edilemeyeceğini unutmayın.',
      'notifications.permissionTitle': 'Yerel bildirim izni',
      'notifications.notNow': 'Şimdi değil',
      'notifications.continue': 'Devam et',
      'notifications.advance': 'Önceden hatırlat',
      'notifications.none': 'Yok',
      'notifications.minutes': '{minutes} dakika',
      'notifications.granted': 'Bildirim izni verildi.',
      'notifications.denied': 'Bildirim izni verilmedi.',
      'notifications.permanentlyDenied':
          'Bildirim izni ayarlardan etkinleştirilmeli.',
      'notifications.unknown': 'Bildirim izin durumu bilinmiyor.',
      'privacy.body': 'Namaz vakitleri ve konum kullanımı cihazda yereldir. Namaz takibi, tesbih, favoriler ve bildirim planlaması cihazda tutulur. Widget verisi yalnızca işletim sistemi uzantısıyla paylaşılır. Satın alma işlemleri Apple/Google mağaza altyapısı üzerinden yürür. Özel sunucu, reklam takibi ve analiz yoktur.',
      'privacy.delete': 'Tüm yerel verileri sil',
      'privacy.deleteTitle': 'Tüm yerel veriler silinsin mi?',
      'privacy.deleteBody': 'Ayarlar, takip geçmişi, tesbih durumu, favoriler, bildirim tercihleri ve widget verisi silinir. Uygulamayla gelen dini içerikler korunur.',
      'privacy.cancel': 'Vazgeç',
      'privacy.confirm': 'Sil',
      'privacy.deleted':
          'Yerel veriler silindi. Güvenli varsayılanlar kullanılacak.',
      'about.version': 'Sürüm 1.0.0',
      'about.prayer': 'Namaz vakitleri çevrimdışı yerel hesaplama ile üretilir. Hicri tarihler tabular hesaplamadır; yerel ay gözlemi ve resmi ilanlarla farklılık gösterebilir.',
      'about.content': 'Günlük ayet, hadis ve dua içerikleri uygulamayla gelen kaynak metadatasını kullanır. Satın almalar Apple App Store veya Google Play altyapısında işlenir.',
      'about.diyanet': 'Diyanet soru akışı resmi dış servisi tarayıcıda açar. Uygulama Diyanet değildir ve dini hüküm vermez.',
      'ramadan.suhoor':
          'Sahur sonu: {time} · seçili hesaplama yöntemindeki sabah vakti',
      'ramadan.iftarRemaining': 'İftara {hours} sa {minutes} dk · {time}',
      'ramadan.iftar': 'İftar vakti: {time}',
    },
    'en': {
      'appTitle': 'Dini',
      'nav.home': 'Home',
      'nav.quran': 'Quran',
      'nav.worship': 'Worship',
      'nav.calendar': 'Calendar',
      'nav.settings': 'Settings',
      'home.greeting': 'May your day be peaceful',
      'home.selectedLocation': 'Selected location',
      'home.nextPrayer': 'Next prayer',
      'home.remaining': '{hours} hr {minutes} min remaining',
      'home.hijri': 'Hijri {date}',
      'home.friday': 'Friday',
      'home.ramadan': 'Ramadan',
      'home.qibla': 'Qibla',
      'home.tasbih': 'Tasbih',
      'home.tracker': 'Prayer tracker',
      'home.calendar': 'Calendar',
      'home.todayTimes': 'Today’s prayer times',
      'home.now': 'NOW',
      'home.next': 'NEXT',
      'home.sunrise': 'Sunrise · not a prayer time',
      'home.verse': 'Verse of the day',
      'home.hadith': 'Hadith of the day',
      'home.prayer': 'Prayer of the day',
      'settings.title': 'Settings',
      'settings.loadError':
          'Settings could not be loaded. Safe defaults are available.',
      'settings.calculation': 'Calculation method',
      'settings.asrMethod': 'Asr method',
      'settings.clock24': '24-hour time',
      'settings.theme': 'Theme',
      'settings.openingTakbir': 'Opening takbir',
      'settings.openingTakbirHint': 'When the app opens, “Allahu Akbar” is recited twice at a very low volume.',
      'settings.language': 'App language',
      'settings.languageHint': 'The language changes immediately.',
      'settings.hijriNotice': 'The Hijri date uses an offline tabular calculation and may differ by one day from local moon sightings and official announcements.',
      'settings.widgetLocation': 'Show location name on widget',
      'settings.widgetLocationHint': 'Prayer times remain visible when off, but the city name is not shared.',
      'settings.widgetLoading': 'Loading widget privacy setting…',
      'settings.widgetDefault': 'Widget location is hidden by default.',
      'settings.notifications': 'Notifications',
      'settings.askDiyanet': 'Ask Diyanet',
      'settings.about': 'About and sources',
      'settings.premium': 'Premium',
      'settings.privacy': 'Privacy Center',
      'language.tr': 'Türkçe',
      'language.en': 'English',
      'language.ar': 'العربية',
      'prayer.fajr': 'Fajr',
      'prayer.sunrise': 'Sunrise',
      'prayer.dhuhr': 'Dhuhr',
      'prayer.asr': 'Asr',
      'prayer.maghrib': 'Maghrib',
      'prayer.isha': 'Isha',
      'month.1': 'January',
      'month.2': 'February',
      'month.3': 'March',
      'month.4': 'April',
      'month.5': 'May',
      'month.6': 'June',
      'month.7': 'July',
      'month.8': 'August',
      'month.9': 'September',
      'month.10': 'October',
      'month.11': 'November',
      'month.12': 'December',
      'calendar.disclaimer': 'The Hijri date uses an offline tabular calculation; observed dates may vary by region and authority.',
      'calendar.previousMonth': 'Previous month',
      'calendar.nextMonth': 'Next month',
      'calendar.today': 'Today',
      'calendar.religiousDay': 'religious day',
      'calendar.selectedDay': 'Selected day',
      'calendar.noEvent': 'No religious event is recorded for this day.',
      'calendar.dateNotice': 'Dates are calculated Islamic calendar dates and may differ from local announcements.',
      'weekday.1': 'Mon',
      'weekday.2': 'Tue',
      'weekday.3': 'Wed',
      'weekday.4': 'Thu',
      'weekday.5': 'Fri',
      'weekday.6': 'Sat',
      'weekday.7': 'Sun',
      'event.ramadan-start': 'Start of Ramadan',
      'event.laylat-al-qadr': 'Laylat al-Qadr',
      'event.eid-al-fitr': 'Eid al-Fitr',
      'event.eid-al-adha': 'Eid al-Adha',
      'event.mawlid': 'Mawlid',
      'event.miraj': 'Al-Isra wal-Miraj',
      'event.berat': 'Laylat al-Bara’at',
      'content.removeFavorite': 'Remove from favorites',
      'content.addFavorite': 'Add to favorites',
      'content.collapse': 'Show less',
      'content.more': 'Read more',
      'content.copy': 'Copy text',
      'content.copied': 'Text copied',
      'content.share': 'Share',
      'tasbih.select': 'Select dhikr',
      'tasbih.target': 'Target',
      'tasbih.decrease': 'Decrease by one',
      'tasbih.increase': 'Increase by one',
      'tasbih.reset': 'Reset',
      'tasbih.haptic': 'Light haptic feedback',
      'tasbih.history': 'Recent sessions',
      'dhikr.subhanallah': 'Subhanallah',
      'dhikr.alhamdulillah': 'Alhamdulillah',
      'dhikr.allahu-akbar': 'Allahu Akbar',
      'dhikr.salawat': 'Salawat',
      'qibla.sensorUnavailable': 'The compass sensor is unavailable. Hold the phone flat and try the calibration motion.',
      'qibla.title': 'Point the top of your phone toward the Kaaba',
      'qibla.ready': 'You are facing the Qibla',
      'qibla.turnRight': 'Turn right {degrees}°',
      'qibla.turnLeft': 'Turn left {degrees}°',
      'qibla.bearings': 'Device {heading}° · Qibla {qibla}°',
      'qibla.calibration': 'Calibrate the compass',
      'qibla.calibrationHint': 'Hold the phone flat and trace a figure eight a few times. Move away from metal objects.',
      'qibla.heading': 'Device heading: {degrees}°{aligned}',
      'qibla.aligned': ' · Aligned',
      'qibla.privacy':
          'Your location stays on this device and is not sent out.',
      'tracker.title': 'Prayer Tracker',
      'tracker.today': 'Today’s prayers',
      'tracker.completed': '{completed} / {total} completed',
      'tracker.privacy': 'Tracking data is stored only on this device using the selected day’s local date.',
      'worship.title': 'Worship Guide',
      'worship.tracker': 'Tracker',
      'worship.prayerGuide': 'How to pray',
      'worship.tabPrayer': 'Prayer',
      'worship.tabWudu': 'Wudu',
      'worship.wudu': 'How to make wudu',
      'worship.alarms': 'Alarms',
      'guide.prayerTitle': 'Five daily prayers guide',
      'guide.prayerIntro': 'Choose a prayer to see its sunnah, fard and witr order and learn the core movements step by step with illustrations.',
      'guide.schoolNotice': 'Some details vary by school. The rakah order follows the common Hanafi presentation used by Diyanet.',
      'guide.rakat': 'rakah',
      'guide.rakatCount': '{count} rakahs',
      'guide.firstSunnah': 'First sunnah',
      'guide.fard': 'Fard',
      'guide.finalSunnah': 'Final sunnah',
      'guide.witr': 'Witr wajib',
      'guide.orderTitle': 'Prayer order',
      'guide.movementsTitle': 'Core flow of one rakah',
      'guide.prayerImageLabel':
          'Eight-stage illustrated guide to prayer movements',
      'guide.prayerStep1': 'Make your intention, face the Qibla and begin the prayer with the opening takbir.',
      'guide.prayerStep2': 'Stand with the hands folded; recite Al-Fatiha and an appropriate surah or verses.',
      'guide.prayerStep3': 'Say “Allahu Akbar” and bow for ruku, keeping the back level and hands on the knees.',
      'guide.prayerStep4':
          'Rise from ruku and pause briefly while standing upright.',
      'guide.prayerStep5': 'Move into sujud; place the forehead and nose, palms, knees and toes correctly.',
      'guide.prayerStep6':
          'Rise from sujud and sit briefly between the two prostrations.',
      'guide.prayerStep7':
          'Perform the second sujud; stand for the next rakah when required.',
      'guide.prayerStep8': 'In the final sitting recite Tashahhud, salawat and supplications, then give salam to both sides.',
      'guide.rakatLabel': 'Rakat {index}',
      'guide.finalSitting': 'Final sitting',
      'guide.recitationsTitle': 'What is recited',
      'guide.recitationsEmpty': 'The Arabic text, transliteration and meaning for this section have not been added yet. Content will be added from a verified source.',
      'guide.transliteration': 'Transliteration',
      'guide.meaning': 'Meaning',
      'recitation.subhaneke.name': 'Subhanaka',
      'recitation.fatiha.name': 'Surah al-Fatiha',
      'recitation.ettehiyyatu.name': 'At-Tahiyyat',
      'recitation.allahummeSalli.name': 'Allahumma salli',
      'recitation.allahummeBarik.name': 'Allahumma barik',
      'recitation.rabbenaAtina.name': 'Rabbana atina',
      'recitation.rabbenagfirli.name': 'Rabbana-ghfir li',
      'recitation.kunut.name': 'The Qunut supplications',
      'recitation.subhaneke.meaning': 'O Allah, You are free of every imperfection, and praise belongs to You. Blessed is Your name, exalted is Your majesty; there is no god but You.',
      'recitation.fatiha.meaning': 'In the name of Allah, the Most Merciful, the Most Compassionate. Praise belongs to Allah, Lord of all the worlds, the Most Merciful, the Most Compassionate, Master of the Day of Judgement. You alone we worship, and from You alone we seek help. Guide us on the straight path — the path of those You have favoured, not of those who incurred anger, nor of those who went astray.',
      'recitation.ettehiyyatu.meaning': 'All greetings, prayers and good deeds belong to Allah. Peace be upon you, O Prophet, and the mercy and blessings of Allah. Peace be upon us and upon the righteous servants of Allah. I bear witness that there is no god but Allah, and I bear witness that Muhammad is His servant and messenger.',
      'recitation.allahummeSalli.meaning': 'O Allah, send Your grace upon Muhammad and the family of Muhammad, as You sent it upon Abraham and the family of Abraham. You are indeed worthy of praise, full of glory.',
      'recitation.allahummeBarik.meaning': 'O Allah, bless Muhammad and the family of Muhammad, as You blessed Abraham and the family of Abraham. You are indeed worthy of praise, full of glory.',
      'recitation.rabbenaAtina.meaning': 'Our Lord, grant us good in this world and good in the hereafter, and protect us from the punishment of the Fire.',
      'recitation.rabbenagfirli.meaning': 'Our Lord, forgive me, my parents and all the believers on the Day of Reckoning.',
      'recitation.kunut.meaning': 'O Allah, we seek Your help, Your forgiveness and Your guidance. We believe in You, turn to You in repentance and rely on You. We praise You for all good. We thank You and are not ungrateful. We part from and abandon those who defy You. — O Allah, You alone we worship; for You alone we pray and prostrate. To You we strive and hasten. We hope for Your mercy and fear Your punishment; indeed Your punishment will reach those who deny You.',
      'recitation.source.ilmihal': 'Source: Presidency of Religious Affairs of Türkiye (Diyanet), Namaz İlmihali.',
      'recitation.source.fatiha': 'Source: The Qur’an, Surah al-Fatiha 1:1-7.',
      'recitation.source.bakara201':
          'Source: The Qur’an, Surah al-Baqarah 2:201.',
      'recitation.source.ibrahim41': 'Source: The Qur’an, Surah Ibrahim 14:41.',
      'guide.beginnerTitle': 'Before you begin',
      'guide.beginnerEssentials': 'The prayer time, wudu, a clean place and clothing, proper covering, the Qibla and intention are the basic preparations.',
      'guide.wuduIntro': 'Make the intention and say Bismillah. Follow the steps below without wasting water.',
      'guide.wuduImageLabel':
          'Illustrated guide showing the eight stages of wudu',
      'guide.wuduStep1':
          'Wash the hands, wrists and between the fingers three times.',
      'guide.wuduStep2': 'Use the right hand to rinse the mouth three times.',
      'guide.wuduStep3': 'Gently rinse and clean the nose three times.',
      'guide.wuduStep4': 'Wash the entire face three times.',
      'guide.wuduStep5':
          'Wash the right then left forearm through the elbow three times.',
      'guide.wuduStep6': 'Wipe part of the head once with wet hands.',
      'guide.wuduStep7':
          'Wipe the ears, then the back of the neck with wet hands.',
      'guide.wuduStep8': 'Wash the right then left foot, including ankles and between toes, three times.',
      'guide.source': 'Source: Presidency of Religious Affairs (Diyanet), Prayer Handbook and High Board of Religious Affairs.',
      'premium.freeTitle': 'Core worship features are free.',
      'premium.freeFeatures': 'Free: prayer times, Qibla, basic notifications, Hijri calendar, daily content, basic tracking, tasbih, basic widget and the default mosque scene.',
      'premium.features': 'Premium: additional scene and widget styles, appearance customization and advanced on-device statistics.',
      'premium.loading': 'Loading store products…',
      'premium.unavailable': 'Store products are currently unavailable, so no price is shown. Free features remain available.',
      'premium.launchTitle': 'Everything is free right now',
      'premium.launchBody': 'During the launch period the app is offered in full: every feature is unlocked and no purchase is needed. A subscription may open later; until then nothing is charged.',
      'quran.comingSoonTitle': 'The Quran screen is coming',
      'quran.comingSoonBody': 'The Quran section is being prepared. Its text will be added from a reliable, clearly licensed source, and will not ship before it is ready.',
      'quran.comingSoonNote': 'Until then you can use prayer times, the qibla, the worship guide and the calendar.',
      'premium.restore': 'Restore purchases',
      'premium.restoreSent': 'The restore request was sent to the store.',
      'premium.active': 'Premium active',
      'premium.cache': 'Store status is displayed using a local UX cache.',
      'notifications.description': 'We can calculate prayer times on your device and send local notifications.',
      'notifications.sound': 'Notification sound',
      'notifications.defaultSound': 'Default',
      'notifications.bundledSound': 'App chime',
      'notifications.silent': 'Silent',
      'notifications.friday': 'Friday reminder',
      'notifications.suhoor': 'Ramadan suhoor/Fajr reminder',
      'notifications.iftar': 'Ramadan iftar/Maghrib reminder',
      'notifications.permissionDone': 'Permission status processed',
      'notifications.managePermission': 'Manage notification permissions',
      'notifications.notice': 'Notifications are scheduled locally. A full-length adhan cannot be guaranteed in the background on every platform.',
      'notifications.permissionTitle': 'Local notification permission',
      'notifications.notNow': 'Not now',
      'notifications.continue': 'Continue',
      'notifications.advance': 'Remind in advance',
      'notifications.none': 'None',
      'notifications.minutes': '{minutes} minutes',
      'notifications.granted': 'Notification permission granted.',
      'notifications.denied': 'Notification permission denied.',
      'notifications.permanentlyDenied':
          'Notification permission must be enabled in Settings.',
      'notifications.unknown': 'Notification permission status is unknown.',
      'privacy.body': 'Prayer times and location use stay on the device. Prayer tracking, tasbih, favorites and notification schedules are stored locally. Widget data is shared only with the operating-system extension. Purchases use Apple or Google store infrastructure. There is no custom backend, ad tracking or analytics.',
      'privacy.delete': 'Delete all local data',
      'privacy.deleteTitle': 'Delete all local data?',
      'privacy.deleteBody': 'Settings, tracking history, tasbih state, favorites, notification preferences and widget data will be deleted. Bundled religious content is preserved.',
      'privacy.cancel': 'Cancel',
      'privacy.confirm': 'Delete',
      'privacy.deleted': 'Local data deleted. Safe defaults will be used.',
      'about.version': 'Version 1.0.0',
      'about.prayer': 'Prayer times are produced with offline on-device calculations. Hijri dates use a tabular calculation and may differ from local moon sightings and official announcements.',
      'about.content': 'Daily verse, hadith and prayer content uses bundled source metadata. Purchases are processed through Apple App Store or Google Play infrastructure.',
      'about.diyanet': 'The Diyanet question flow opens the official external service in a browser. This app is not Diyanet and does not issue religious rulings.',
      'ramadan.suhoor':
          'Suhoor ends: {time} · Fajr under the selected calculation method',
      'ramadan.iftarRemaining': '{hours} hr {minutes} min until iftar · {time}',
      'ramadan.iftar': 'Iftar time: {time}',
    },
    'ar': {
      'appTitle': 'ديني',
      'nav.home': 'الرئيسية',
      'nav.quran': 'القرآن',
      'nav.worship': 'العبادة',
      'nav.calendar': 'التقويم',
      'nav.settings': 'الإعدادات',
      'home.greeting': 'يومك مفعم بالسكينة',
      'home.selectedLocation': 'الموقع المحدد',
      'home.nextPrayer': 'الصلاة القادمة',
      'home.remaining': 'متبقي {hours} س {minutes} د',
      'home.hijri': 'هجري {date}',
      'home.friday': 'الجمعة',
      'home.ramadan': 'رمضان',
      'home.qibla': 'القبلة',
      'home.tasbih': 'التسبيح',
      'home.tracker': 'متابعة الصلاة',
      'home.calendar': 'التقويم',
      'home.todayTimes': 'مواقيت اليوم',
      'home.now': 'الآن',
      'home.next': 'القادمة',
      'home.sunrise': 'الشروق · ليس وقت صلاة',
      'home.verse': 'آية اليوم',
      'home.hadith': 'حديث اليوم',
      'home.prayer': 'دعاء اليوم',
      'settings.title': 'الإعدادات',
      'settings.loadError':
          'تعذر تحميل الإعدادات. يمكن استخدام الإعدادات الآمنة الافتراضية.',
      'settings.calculation': 'طريقة الحساب',
      'settings.asrMethod': 'طريقة حساب العصر',
      'settings.clock24': 'نظام 24 ساعة',
      'settings.theme': 'المظهر',
      'settings.openingTakbir': 'تكبيرة الافتتاح',
      'settings.openingTakbirHint':
          'عند فتح التطبيق تُقرأ «الله أكبر» مرتين بصوت منخفض جدًا.',
      'settings.language': 'لغة التطبيق',
      'settings.languageHint': 'يتم تغيير اللغة فورًا.',
      'settings.hijriNotice': 'يعرض التاريخ الهجري بحساب جدولي دون اتصال، وقد يختلف يومًا واحدًا حسب رؤية الهلال والإعلانات الرسمية.',
      'settings.widgetLocation': 'إظهار اسم الموقع في الأداة',
      'settings.widgetLocationHint':
          'عند إيقافه تظهر مواقيت الصلاة دون مشاركة اسم المدينة.',
      'settings.widgetLoading': 'جارٍ تحميل إعداد خصوصية الأداة…',
      'settings.widgetDefault': 'إخفاء الموقع في الأداة هو الإعداد الافتراضي.',
      'settings.notifications': 'الإشعارات',
      'settings.askDiyanet': 'اسأل رئاسة الشؤون الدينية',
      'settings.about': 'حول التطبيق والمصادر',
      'settings.premium': 'المميز',
      'settings.privacy': 'مركز الخصوصية',
      'language.tr': 'Türkçe',
      'language.en': 'English',
      'language.ar': 'العربية',
      'prayer.fajr': 'الفجر',
      'prayer.sunrise': 'الشروق',
      'prayer.dhuhr': 'الظهر',
      'prayer.asr': 'العصر',
      'prayer.maghrib': 'المغرب',
      'prayer.isha': 'العشاء',
      'month.1': 'يناير',
      'month.2': 'فبراير',
      'month.3': 'مارس',
      'month.4': 'أبريل',
      'month.5': 'مايو',
      'month.6': 'يونيو',
      'month.7': 'يوليو',
      'month.8': 'أغسطس',
      'month.9': 'سبتمبر',
      'month.10': 'أكتوبر',
      'month.11': 'نوفمبر',
      'month.12': 'ديسمبر',
      'calendar.disclaimer': 'يعرض التاريخ الهجري بحساب جدولي دون اتصال، وقد تختلف التواريخ المرصودة حسب المنطقة والجهة الرسمية.',
      'calendar.previousMonth': 'الشهر السابق',
      'calendar.nextMonth': 'الشهر التالي',
      'calendar.today': 'اليوم',
      'calendar.religiousDay': 'مناسبة دينية',
      'calendar.selectedDay': 'اليوم المحدد',
      'calendar.noEvent': 'لا توجد مناسبة دينية مسجلة لهذا اليوم.',
      'calendar.dateNotice': 'هذه تواريخ محسوبة وفق التقويم الإسلامي وقد تختلف عن الإعلانات المحلية.',
      'weekday.1': 'ن',
      'weekday.2': 'ث',
      'weekday.3': 'ر',
      'weekday.4': 'خ',
      'weekday.5': 'ج',
      'weekday.6': 'س',
      'weekday.7': 'ح',
      'event.ramadan-start': 'بداية رمضان',
      'event.laylat-al-qadr': 'ليلة القدر',
      'event.eid-al-fitr': 'عيد الفطر',
      'event.eid-al-adha': 'عيد الأضحى',
      'event.mawlid': 'المولد النبوي',
      'event.miraj': 'ليلة الإسراء والمعراج',
      'event.berat': 'ليلة النصف من شعبان',
      'content.removeFavorite': 'إزالة من المفضلة',
      'content.addFavorite': 'إضافة إلى المفضلة',
      'content.collapse': 'عرض أقل',
      'content.more': 'قراءة المزيد',
      'content.copy': 'نسخ النص',
      'content.copied': 'تم نسخ النص',
      'content.share': 'مشاركة',
      'tasbih.select': 'اختر الذكر',
      'tasbih.target': 'الهدف',
      'tasbih.decrease': 'إنقاص واحد',
      'tasbih.increase': 'زيادة واحد',
      'tasbih.reset': 'إعادة الضبط',
      'tasbih.haptic': 'اهتزاز خفيف',
      'tasbih.history': 'الجلسات الأخيرة',
      'dhikr.subhanallah': 'سبحان الله',
      'dhikr.alhamdulillah': 'الحمد لله',
      'dhikr.allahu-akbar': 'الله أكبر',
      'dhikr.salawat': 'الصلاة على النبي',
      'qibla.sensorUnavailable': 'مستشعر البوصلة غير متاح. أمسك الهاتف بشكل مستوٍ وجرّب حركة المعايرة.',
      'qibla.title': 'وجّه أعلى الهاتف نحو الكعبة',
      'qibla.ready': 'أنت متجه إلى القبلة',
      'qibla.turnRight': 'اتجه يمينًا {degrees}°',
      'qibla.turnLeft': 'اتجه يسارًا {degrees}°',
      'qibla.bearings': 'الهاتف {heading}° · القبلة {qibla}°',
      'qibla.calibration': 'معايرة البوصلة',
      'qibla.calibrationHint':
          'أمسك الهاتف أفقيًا وحرّكه على شكل رقم 8 عدة مرات وابتعد عن المعادن.',
      'qibla.heading': 'اتجاه الجهاز: {degrees}°{aligned}',
      'qibla.aligned': ' · بمحاذاة القبلة',
      'qibla.privacy': 'يبقى موقعك على هذا الجهاز ولا يتم إرساله.',
      'tracker.title': 'متابعة الصلاة',
      'tracker.today': 'صلوات اليوم',
      'tracker.completed': 'تم إكمال {completed} من {total}',
      'tracker.privacy': 'تُحفظ بيانات المتابعة على هذا الجهاز فقط وفق التاريخ المحلي لليوم المحدد.',
      'worship.title': 'دليل العبادة',
      'worship.tracker': 'المتابعة',
      'worship.prayerGuide': 'كيفية الصلاة',
      'worship.tabPrayer': 'الصلاة',
      'worship.tabWudu': 'الوضوء',
      'worship.wudu': 'كيفية الوضوء',
      'worship.alarms': 'المنبهات',
      'guide.prayerTitle': 'دليل الصلوات الخمس',
      'guide.prayerIntro': 'اختر الصلاة لمعرفة ترتيب السنن والفرض والوتر وتعلّم الحركات الأساسية خطوة بخطوة بالصور.',
      'guide.schoolNotice': 'قد تختلف بعض التفاصيل باختلاف المذاهب. ترتيب الركعات يتبع العرض الحنفي الشائع لدى رئاسة الشؤون الدينية.',
      'guide.rakat': 'ركعة',
      'guide.rakatCount': '{count} ركعات',
      'guide.firstSunnah': 'السنة الأولى',
      'guide.fard': 'الفرض',
      'guide.finalSunnah': 'السنة الأخيرة',
      'guide.witr': 'الوتر الواجب',
      'guide.orderTitle': 'ترتيب الصلاة',
      'guide.movementsTitle': 'المراحل الأساسية للركعة',
      'guide.prayerImageLabel': 'دليل مصور من ثماني مراحل لحركات الصلاة',
      'guide.prayerStep1': 'انوِ الصلاة واستقبل القبلة وابدأ بتكبيرة الإحرام.',
      'guide.prayerStep2': 'قف واضعًا اليدين واقرأ الفاتحة وما تيسر من القرآن.',
      'guide.prayerStep3':
          'قل «الله أكبر» واركع مع استواء الظهر ووضع اليدين على الركبتين.',
      'guide.prayerStep4': 'ارفع من الركوع وقف معتدلًا لحظة قصيرة.',
      'guide.prayerStep5':
          'اسجد واضعًا الجبهة والأنف والكفين والركبتين وأطراف القدمين.',
      'guide.prayerStep6': 'ارفع من السجود واجلس قليلًا بين السجدتين.',
      'guide.prayerStep7':
          'اسجد السجدة الثانية ثم قم للركعة التالية عند الحاجة.',
      'guide.prayerStep8':
          'في الجلوس الأخير اقرأ التشهد والصلاة والدعاء ثم سلّم عن الجانبين.',
      'guide.rakatLabel': 'الركعة {index}',
      'guide.finalSitting': 'الجلوس الأخير',
      'guide.recitationsTitle': 'ما يُقرأ',
      'guide.recitationsEmpty': 'لم تُضَف بعد النصوص العربية والنطق والمعنى لهذا القسم. ستُضاف من مصدر موثوق.',
      'guide.transliteration': 'النطق',
      'guide.meaning': 'المعنى',
      'recitation.subhaneke.name': 'سبحانك',
      'recitation.fatiha.name': 'سورة الفاتحة',
      'recitation.ettehiyyatu.name': 'التحيات',
      'recitation.allahummeSalli.name': 'اللهم صلِّ',
      'recitation.allahummeBarik.name': 'اللهم بارك',
      'recitation.rabbenaAtina.name': 'ربنا آتنا',
      'recitation.rabbenagfirli.name': 'ربنا اغفر لي',
      'recitation.kunut.name': 'دعاء القنوت',
      'recitation.subhaneke.meaning':
          'تنزيهًا لك اللهم وبحمدك، تبارك اسمك، وتعالى جدك، ولا إله غيرك.',
      'recitation.fatiha.meaning': 'بسم الله الرحمن الرحيم. الحمد لله رب العالمين، الرحمن الرحيم، مالك يوم الدين. إياك نعبد وإياك نستعين. اهدنا الصراط المستقيم، صراط الذين أنعمت عليهم، غير المغضوب عليهم ولا الضالين.',
      'recitation.ettehiyyatu.meaning': 'التحيات والصلوات والطيبات كلها لله. السلام عليك أيها النبي ورحمة الله وبركاته. السلام علينا وعلى عباد الله الصالحين. أشهد أن لا إله إلا الله وأشهد أن محمدًا عبده ورسوله.',
      'recitation.allahummeSalli.meaning': 'اللهم صلِّ على محمد وعلى آل محمد كما صليت على إبراهيم وعلى آل إبراهيم، إنك حميد مجيد.',
      'recitation.allahummeBarik.meaning': 'اللهم بارك على محمد وعلى آل محمد كما باركت على إبراهيم وعلى آل إبراهيم، إنك حميد مجيد.',
      'recitation.rabbenaAtina.meaning':
          'ربنا آتنا في الدنيا حسنة وفي الآخرة حسنة وقنا عذاب النار.',
      'recitation.rabbenagfirli.meaning':
          'ربنا اغفر لي ولوالديَّ وللمؤمنين يوم يقوم الحساب.',
      'recitation.kunut.meaning': 'اللهم إنا نستعينك ونستغفرك ونستهديك، ونؤمن بك ونتوب إليك، ونتوكل عليك ونثني عليك الخير كله، نشكرك ولا نكفرك، ونخلع ونترك من يفجرك. — اللهم إياك نعبد ولك نصلي ونسجد، وإليك نسعى ونحفد، نرجو رحمتك ونخشى عذابك، إن عذابك بالكفار ملحق.',
      'recitation.source.ilmihal':
          'المصدر: رئاسة الشؤون الدينية التركية، كتاب أحكام الصلاة.',
      'recitation.source.fatiha': 'المصدر: القرآن الكريم، سورة الفاتحة ١-٧.',
      'recitation.source.bakara201': 'المصدر: القرآن الكريم، سورة البقرة ٢٠١.',
      'recitation.source.ibrahim41': 'المصدر: القرآن الكريم، سورة إبراهيم ٤١.',
      'guide.beginnerTitle': 'قبل البدء',
      'guide.beginnerEssentials': 'دخول الوقت والوضوء وطهارة الثوب والمكان وستر العورة واستقبال القبلة والنية هي الاستعدادات الأساسية.',
      'guide.wuduIntro':
          'انوِ الوضوء وقل بسم الله ثم اتبع الخطوات دون إسراف في الماء.',
      'guide.wuduImageLabel': 'دليل مصور يوضح مراحل الوضوء الثماني',
      'guide.wuduStep1': 'اغسل اليدين والرسغين وبين الأصابع ثلاث مرات.',
      'guide.wuduStep2': 'تمضمض بالماء باليد اليمنى ثلاث مرات.',
      'guide.wuduStep3': 'استنشق الماء بلطف ونظف الأنف ثلاث مرات.',
      'guide.wuduStep4': 'اغسل الوجه كاملًا ثلاث مرات.',
      'guide.wuduStep5': 'اغسل الذراع اليمنى ثم اليسرى مع المرفقين ثلاث مرات.',
      'guide.wuduStep6': 'امسح جزءًا من الرأس مرة واحدة باليدين المبللتين.',
      'guide.wuduStep7': 'امسح الأذنين ثم مؤخرة الرقبة باليدين المبللتين.',
      'guide.wuduStep8':
          'اغسل القدم اليمنى ثم اليسرى مع الكعبين وبين الأصابع ثلاث مرات.',
      'guide.source': 'المصدر: رئاسة الشؤون الدينية التركية، دليل الصلاة والمجلس الأعلى للشؤون الدينية.',
      'premium.freeTitle': 'ميزات العبادة الأساسية مجانية.',
      'premium.freeFeatures': 'مجانًا: مواقيت الصلاة والقبلة والإشعارات الأساسية والتقويم الهجري والمحتوى اليومي والمتابعة الأساسية والتسبيح والأداة الأساسية ومشهد المسجد الافتراضي.',
      'premium.features': 'المميز: مشاهد وأشكال إضافية للأداة وتخصيص المظهر وإحصاءات محلية متقدمة.',
      'premium.loading': 'جارٍ تحميل منتجات المتجر…',
      'premium.unavailable': 'منتجات المتجر غير متاحة حاليًا، لذلك لا يظهر السعر. تبقى الميزات المجانية متاحة.',
      'premium.launchTitle': 'كل شيء مجاني الآن',
      'premium.launchBody': 'يُقدَّم التطبيق كاملًا خلال فترة الإطلاق: جميع الميزات مفتوحة ولا حاجة إلى أي شراء. قد يُفتح الاشتراك لاحقًا، ولا يُحصَّل أي مبلغ حتى ذلك الحين.',
      'quran.comingSoonTitle': 'شاشة القرآن قريبًا',
      'quran.comingSoonBody': 'يجري إعداد قسم القرآن. ستُضاف النصوص من مصدر موثوق وواضح الترخيص، ولن تُنشر قبل أن تكون جاهزة.',
      'quran.comingSoonNote': 'حتى ذلك الحين يمكنك استخدام مواقيت الصلاة والقبلة ودليل العبادة والتقويم.',
      'premium.restore': 'استعادة المشتريات',
      'premium.restoreSent': 'تم إرسال طلب الاستعادة إلى المتجر.',
      'premium.active': 'الاشتراك المميز نشط',
      'premium.cache': 'تُعرض حالة المتجر باستخدام ذاكرة محلية مؤقتة.',
      'notifications.description':
          'يمكننا حساب مواقيت الصلاة على جهازك وإرسال إشعارات محلية.',
      'notifications.sound': 'صوت الإشعار',
      'notifications.defaultSound': 'الافتراضي',
      'notifications.bundledSound': 'نغمة التطبيق',
      'notifications.silent': 'صامت',
      'notifications.friday': 'تذكير الجمعة',
      'notifications.suhoor': 'تذكير سحور رمضان والفجر',
      'notifications.iftar': 'تذكير إفطار رمضان والمغرب',
      'notifications.permissionDone': 'تمت معالجة حالة الإذن',
      'notifications.managePermission': 'إدارة أذونات الإشعارات',
      'notifications.notice': 'تُجدول الإشعارات محليًا. لا يمكن ضمان تشغيل الأذان كاملًا في الخلفية على جميع المنصات.',
      'notifications.permissionTitle': 'إذن الإشعارات المحلية',
      'notifications.notNow': 'ليس الآن',
      'notifications.continue': 'متابعة',
      'notifications.advance': 'التذكير مسبقًا',
      'notifications.none': 'بدون',
      'notifications.minutes': '{minutes} دقائق',
      'notifications.granted': 'تم منح إذن الإشعارات.',
      'notifications.denied': 'لم يتم منح إذن الإشعارات.',
      'notifications.permanentlyDenied':
          'يجب تفعيل إذن الإشعارات من الإعدادات.',
      'notifications.unknown': 'حالة إذن الإشعارات غير معروفة.',
      'privacy.body': 'تبقى مواقيت الصلاة واستخدام الموقع على الجهاز. تُحفظ متابعة الصلاة والتسبيح والمفضلة وجدولة الإشعارات محليًا. لا تُشارك بيانات الأداة إلا مع امتداد نظام التشغيل. تتم المشتريات عبر بنية متجر Apple أو Google. لا توجد خوادم خاصة أو تحليلات أو تتبع إعلاني.',
      'privacy.delete': 'حذف جميع البيانات المحلية',
      'privacy.deleteTitle': 'هل تريد حذف جميع البيانات المحلية؟',
      'privacy.deleteBody': 'ستُحذف الإعدادات وسجل المتابعة وحالة التسبيح والمفضلة وتفضيلات الإشعارات وبيانات الأداة. سيُحفظ المحتوى الديني المضمّن.',
      'privacy.cancel': 'إلغاء',
      'privacy.confirm': 'حذف',
      'privacy.deleted':
          'تم حذف البيانات المحلية. ستُستخدم الإعدادات الآمنة الافتراضية.',
      'about.version': 'الإصدار 1.0.0',
      'about.prayer': 'تُحسب مواقيت الصلاة محليًا دون اتصال. يستخدم التاريخ الهجري حسابًا جدوليًا وقد يختلف عن رؤية الهلال والإعلانات الرسمية.',
      'about.content': 'يستخدم محتوى الآية والحديث والدعاء اليومي بيانات المصادر المضمّنة. تتم المشتريات عبر Apple App Store أو Google Play.',
      'about.diyanet': 'يفتح مسار سؤال رئاسة الشؤون الدينية الخدمة الرسمية الخارجية في المتصفح. هذا التطبيق ليس تابعًا للرئاسة ولا يصدر أحكامًا دينية.',
      'ramadan.suhoor':
          'نهاية السحور: {time} · وقت الفجر وفق طريقة الحساب المحددة',
      'ramadan.iftarRemaining': 'متبقي للإفطار {hours} س {minutes} د · {time}',
      'ramadan.iftar': 'وقت الإفطار: {time}',
    },
  };
}

extension AppLocalizationsContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
