import 'package:flutter/material.dart';

/// App-specific copy for the three languages supported by Dini.
class AppLocalizations {
  final Locale locale;

  const AppLocalizations(this.locale);

  static const supportedLocales = <Locale>[
    Locale('tr'),
    Locale('en'),
    Locale('ar'),
  ];

  static AppLocalizations of(BuildContext context) =>
      AppLocalizations(Localizations.localeOf(context));

  String get languageCode =>
      _strings.containsKey(locale.languageCode) ? locale.languageCode : 'tr';

  String text(String key, [Map<String, Object> values = const {}]) {
    var value = _strings[languageCode]?[key] ?? _strings['tr']?[key] ?? key;
    for (final entry in values.entries) {
      value = value.replaceAll('{${entry.key}}', '${entry.value}');
    }
    return value;
  }

  /// Bir dilin tanımlı anahtar kümesi. Üç dil arasındaki pariteyi test eden
  /// `localization_test.dart` tarafından kullanılır.
  @visibleForTesting
  static Set<String> keysFor(String languageCode) =>
      _strings[languageCode]?.keys.toSet() ?? const <String>{};

  String prayer(String name) => text('prayer.$name');

  String month(int month) => text('month.$month');

  static const Map<String, Map<String, String>> _strings = {
    'tr': {
      'appTitle': 'Dini',
      'nav.home': 'Ana Sayfa',
      'nav.quran': 'Kuran',
      'nav.worship': 'İbadet',
      'nav.calendar': 'Takvim',
      'nav.settings': 'Ayarlar',
      'home.greeting': 'Huzurlu bir gün',
      'home.selectedLocation': 'Seçili konum',
      'home.nextPrayer': 'Sıradaki namaz',
      'home.remaining': '{hours} sa {minutes} dk kaldı',
      'home.hijri': 'Hicri {date}',
      'home.friday': 'Cuma',
      'home.ramadan': 'Ramazan',
      'home.qibla': 'Kıble',
      'home.tasbih': 'Tesbih',
      'home.tracker': 'Namaz takibi',
      'home.calendar': 'Takvim',
      'home.todayTimes': 'Bugünün vakitleri',
      'home.now': 'ŞİMDİ',
      'home.next': 'SIRADA',
      'home.sunrise': 'Güneş doğuşu · namaz vakti değildir',
      'home.verse': 'Günün ayeti',
      'home.hadith': 'Günün hadisi',
      'home.prayer': 'Günün duası',
      'settings.title': 'Ayarlar',
      'settings.loadError':
          'Ayarlar yüklenemedi. Güvenli varsayılanlar kullanılabilir.',
      'settings.calculation': 'Hesaplama yöntemi',
      'settings.asrMethod': 'İkindi yöntemi',
      'settings.clock24': '24 saat biçimi',
      'settings.theme': 'Tema',
      'settings.language': 'Uygulama dili',
      'settings.languageHint': 'Dil değişikliği anında uygulanır.',
      'settings.hijriNotice': 'Hicri tarih offline tabular hesaplama ile gösterilir; yerel ay gözlemi ve resmi ilanlarla bir gün farklılık gösterebilir.',
      'settings.widgetLocation': 'Widget’ta konum adını göster',
      'settings.widgetLocationHint':
          'Kapalıyken namaz vakitleri gösterilir, şehir adı paylaşılmaz.',
      'settings.widgetLoading': 'Widget gizlilik ayarı yükleniyor…',
      'settings.widgetDefault': 'Widget gizliliği varsayılan olarak kapalı.',
      'settings.notifications': 'Bildirimler',
      'settings.askDiyanet': 'Diyanet’e Soru Sor',
      'settings.about': 'Hakkında ve kaynaklar',
      'settings.premium': 'Premium',
      'settings.privacy': 'Gizlilik Merkezi',
      'language.tr': 'Türkçe',
      'language.en': 'English',
      'language.ar': 'العربية',
      'prayer.fajr': 'Sabah',
      'prayer.sunrise': 'Güneş',
      'prayer.dhuhr': 'Öğle',
      'prayer.asr': 'İkindi',
      'prayer.maghrib': 'Akşam',
      'prayer.isha': 'Yatsı',
      'month.1': 'Ocak',
      'month.2': 'Şubat',
      'month.3': 'Mart',
      'month.4': 'Nisan',
      'month.5': 'Mayıs',
      'month.6': 'Haziran',
      'month.7': 'Temmuz',
      'month.8': 'Ağustos',
      'month.9': 'Eylül',
      'month.10': 'Ekim',
      'month.11': 'Kasım',
      'month.12': 'Aralık',
      'calendar.disclaimer': 'Hicri tarih offline tabular hesaplama ile gösterilir; gözlemlenen tarihler bölgeye ve otoriteye göre değişebilir.',
      'calendar.previousMonth': 'Önceki ay',
      'calendar.nextMonth': 'Sonraki ay',
      'calendar.today': 'Bugün',
      'calendar.religiousDay': 'dini gün',
      'calendar.selectedDay': 'Seçili gün',
      'calendar.noEvent': 'Bu gün için kayıtlı dini etkinlik yok.',
      'calendar.dateNotice': 'Tarihler hesaplanmış İslami takvim tarihidir; yerel ilanlarla farklılık gösterebilir.',
      'weekday.1': 'Pzt',
      'weekday.2': 'Sal',
      'weekday.3': 'Çar',
      'weekday.4': 'Per',
      'weekday.5': 'Cum',
      'weekday.6': 'Cmt',
      'weekday.7': 'Paz',
      'event.ramadan-start': 'Ramazan başlangıcı',
      'event.laylat-al-qadr': 'Kadir Gecesi',
      'event.eid-al-fitr': 'Ramazan Bayramı',
      'event.eid-al-adha': 'Kurban Bayramı',
      'event.mawlid': 'Mevlid Kandili',
      'event.miraj': 'Miraç Kandili',
      'event.berat': 'Berat Kandili',
      'content.removeFavorite': 'Favoriden çıkar',
      'content.addFavorite': 'Favoriye ekle',
      'content.collapse': 'Daralt',
      'content.more': 'Devamını gör',
      'content.copy': 'Metni kopyala',
      'content.copied': 'Metin kopyalandı',
      'content.share': 'Paylaş',
      'tasbih.select': 'Zikir seçimi',
      'tasbih.target': 'Hedef',
      'tasbih.decrease': 'Bir azalt',
      'tasbih.increase': 'Bir artır',
      'tasbih.reset': 'Sıfırla',
      'tasbih.haptic': 'Hafif dokunsal geri bildirim',
      'tasbih.history': 'Son oturumlar',
      'dhikr.subhanallah': 'Sübhanallah',
      'dhikr.alhamdulillah': 'Elhamdülillah',
      'dhikr.allahu-akbar': 'Allahu Ekber',
      'dhikr.salawat': 'Salavat',
      'qibla.sensorUnavailable': 'Pusula sensörü kullanılamıyor. Telefonu düz tutup kalibrasyon hareketini deneyin.',
      'qibla.heading': 'Cihaz yönü: {degrees}°{aligned}',
      'qibla.aligned': ' · Hizalı',
      'qibla.privacy': 'Konum cihazda tutulur; dışarı gönderilmez.',
      'tracker.title': 'Namaz Takibi',
      'tracker.completed': '{completed} / {total} tamamlandı',
      'tracker.privacy': 'Takip verileri seçili günün yerel tarihine göre yalnızca cihazda saklanır.',
      'premium.freeTitle': 'Temel ibadet özellikleri ücretsizdir.',
      'premium.freeFeatures': 'Ücretsiz: namaz vakitleri, kıble, temel bildirimler, Hicri takvim, günlük içerik, temel takip, tesbih, temel widget ve varsayılan cami sahnesi.',
      'premium.features': 'Premium: ek sahne ve widget görünümleri, görünüm kişiselleştirme ve yerel gelişmiş istatistikler.',
      'premium.loading': 'Mağaza ürünleri yükleniyor…',
      'premium.unavailable': 'Mağaza ürünleri şu anda kullanılamıyor. Fiyat gösterilmedi. Ücretsiz özellikler kullanılmaya devam eder.',
      'premium.restore': 'Satın alımları geri yükle',
      'premium.restoreSent': 'Geri yükleme isteği mağazaya gönderildi.',
      'premium.active': 'Premium etkin',
      'premium.cache':
          'Mağaza durumu yerel kullanıcı deneyimi önbelleğiyle gösteriliyor.',
      'notifications.description': 'Namaz vakitlerini cihazınızda hesaplayarak size yerel bildirim gönderebiliriz.',
      'notifications.sound': 'Bildirim sesi',
      'notifications.defaultSound': 'Varsayılan',
      'notifications.bundledSound': 'Hazır ses (platform izin verirse)',
      'notifications.silent': 'Sessiz',
      'notifications.friday': 'Cuma hatırlatıcısı',
      'notifications.suhoor': 'Ramazan sahur/sabah yaklaşma',
      'notifications.iftar': 'Ramazan iftar/akşam yaklaşma',
      'notifications.permissionDone': 'İzin durumu işlendi',
      'notifications.managePermission': 'Bildirim izinlerini yönet',
      'notifications.notice': 'Bildirimler yerel olarak planlanır. Tam uzunlukta ezan sesinin arka planda her platformda garanti edilemeyeceğini unutmayın.',
      'notifications.permissionTitle': 'Yerel bildirim izni',
      'notifications.notNow': 'Şimdi değil',
      'notifications.continue': 'Devam et',
      'notifications.advance': 'Önceden hatırlat',
      'notifications.none': 'Yok',
      'notifications.minutes': '{minutes} dakika',
      'notifications.granted': 'Bildirim izni verildi.',
      'notifications.denied': 'Bildirim izni verilmedi.',
      'notifications.permanentlyDenied':
          'Bildirim izni ayarlardan etkinleştirilmeli.',
      'notifications.unknown': 'Bildirim izin durumu bilinmiyor.',
      'privacy.body': 'Namaz vakitleri ve konum kullanımı cihazda yereldir. Namaz takibi, tesbih, favoriler ve bildirim planlaması cihazda tutulur. Widget verisi yalnızca işletim sistemi uzantısıyla paylaşılır. Satın alma işlemleri Apple/Google mağaza altyapısı üzerinden yürür. Özel sunucu, reklam takibi ve analiz yoktur.',
      'privacy.delete': 'Tüm yerel verileri sil',
      'privacy.deleteTitle': 'Tüm yerel veriler silinsin mi?',
      'privacy.deleteBody': 'Ayarlar, takip geçmişi, tesbih durumu, favoriler, bildirim tercihleri ve widget verisi silinir. Uygulamayla gelen dini içerikler korunur.',
      'privacy.cancel': 'Vazgeç',
      'privacy.confirm': 'Sil',
      'privacy.deleted':
          'Yerel veriler silindi. Güvenli varsayılanlar kullanılacak.',
      'about.version': 'Sürüm 1.0.0',
      'about.prayer': 'Namaz vakitleri çevrimdışı yerel hesaplama ile üretilir. Hicri tarihler tabular hesaplamadır; yerel ay gözlemi ve resmi ilanlarla farklılık gösterebilir.',
      'about.content': 'Günlük ayet, hadis ve dua içerikleri uygulamayla gelen kaynak metadatasını kullanır. Satın almalar Apple App Store veya Google Play altyapısında işlenir.',
      'about.diyanet': 'Diyanet soru akışı resmi dış servisi tarayıcıda açar. Uygulama Diyanet değildir ve dini hüküm vermez.',
      'placeholder': '{title} temel ekranı hazır; işlevsel özellik sonraki adımda eklenecek.',
      'ramadan.suhoor':
          'Sahur sonu: {time} · seçili hesaplama yöntemindeki sabah vakti',
      'ramadan.iftarRemaining': 'İftara {hours} sa {minutes} dk · {time}',
      'ramadan.iftar': 'İftar vakti: {time}',
    },
    'en': {
      'appTitle': 'Dini',
      'nav.home': 'Home',
      'nav.quran': 'Quran',
      'nav.worship': 'Worship',
      'nav.calendar': 'Calendar',
      'nav.settings': 'Settings',
      'home.greeting': 'May your day be peaceful',
      'home.selectedLocation': 'Selected location',
      'home.nextPrayer': 'Next prayer',
      'home.remaining': '{hours} hr {minutes} min remaining',
      'home.hijri': 'Hijri {date}',
      'home.friday': 'Friday',
      'home.ramadan': 'Ramadan',
      'home.qibla': 'Qibla',
      'home.tasbih': 'Tasbih',
      'home.tracker': 'Prayer tracker',
      'home.calendar': 'Calendar',
      'home.todayTimes': 'Today’s prayer times',
      'home.now': 'NOW',
      'home.next': 'NEXT',
      'home.sunrise': 'Sunrise · not a prayer time',
      'home.verse': 'Verse of the day',
      'home.hadith': 'Hadith of the day',
      'home.prayer': 'Prayer of the day',
      'settings.title': 'Settings',
      'settings.loadError':
          'Settings could not be loaded. Safe defaults are available.',
      'settings.calculation': 'Calculation method',
      'settings.asrMethod': 'Asr method',
      'settings.clock24': '24-hour time',
      'settings.theme': 'Theme',
      'settings.language': 'App language',
      'settings.languageHint': 'The language changes immediately.',
      'settings.hijriNotice': 'The Hijri date uses an offline tabular calculation and may differ by one day from local moon sightings and official announcements.',
      'settings.widgetLocation': 'Show location name on widget',
      'settings.widgetLocationHint': 'Prayer times remain visible when off, but the city name is not shared.',
      'settings.widgetLoading': 'Loading widget privacy setting…',
      'settings.widgetDefault': 'Widget location is hidden by default.',
      'settings.notifications': 'Notifications',
      'settings.askDiyanet': 'Ask Diyanet',
      'settings.about': 'About and sources',
      'settings.premium': 'Premium',
      'settings.privacy': 'Privacy Center',
      'language.tr': 'Türkçe',
      'language.en': 'English',
      'language.ar': 'العربية',
      'prayer.fajr': 'Fajr',
      'prayer.sunrise': 'Sunrise',
      'prayer.dhuhr': 'Dhuhr',
      'prayer.asr': 'Asr',
      'prayer.maghrib': 'Maghrib',
      'prayer.isha': 'Isha',
      'month.1': 'January',
      'month.2': 'February',
      'month.3': 'March',
      'month.4': 'April',
      'month.5': 'May',
      'month.6': 'June',
      'month.7': 'July',
      'month.8': 'August',
      'month.9': 'September',
      'month.10': 'October',
      'month.11': 'November',
      'month.12': 'December',
      'calendar.disclaimer': 'The Hijri date uses an offline tabular calculation; observed dates may vary by region and authority.',
      'calendar.previousMonth': 'Previous month',
      'calendar.nextMonth': 'Next month',
      'calendar.today': 'Today',
      'calendar.religiousDay': 'religious day',
      'calendar.selectedDay': 'Selected day',
      'calendar.noEvent': 'No religious event is recorded for this day.',
      'calendar.dateNotice': 'Dates are calculated Islamic calendar dates and may differ from local announcements.',
      'weekday.1': 'Mon',
      'weekday.2': 'Tue',
      'weekday.3': 'Wed',
      'weekday.4': 'Thu',
      'weekday.5': 'Fri',
      'weekday.6': 'Sat',
      'weekday.7': 'Sun',
      'event.ramadan-start': 'Start of Ramadan',
      'event.laylat-al-qadr': 'Laylat al-Qadr',
      'event.eid-al-fitr': 'Eid al-Fitr',
      'event.eid-al-adha': 'Eid al-Adha',
      'event.mawlid': 'Mawlid',
      'event.miraj': 'Al-Isra wal-Miraj',
      'event.berat': 'Laylat al-Bara’at',
      'content.removeFavorite': 'Remove from favorites',
      'content.addFavorite': 'Add to favorites',
      'content.collapse': 'Show less',
      'content.more': 'Read more',
      'content.copy': 'Copy text',
      'content.copied': 'Text copied',
      'content.share': 'Share',
      'tasbih.select': 'Select dhikr',
      'tasbih.target': 'Target',
      'tasbih.decrease': 'Decrease by one',
      'tasbih.increase': 'Increase by one',
      'tasbih.reset': 'Reset',
      'tasbih.haptic': 'Light haptic feedback',
      'tasbih.history': 'Recent sessions',
      'dhikr.subhanallah': 'Subhanallah',
      'dhikr.alhamdulillah': 'Alhamdulillah',
      'dhikr.allahu-akbar': 'Allahu Akbar',
      'dhikr.salawat': 'Salawat',
      'qibla.sensorUnavailable': 'The compass sensor is unavailable. Hold the phone flat and try the calibration motion.',
      'qibla.heading': 'Device heading: {degrees}°{aligned}',
      'qibla.aligned': ' · Aligned',
      'qibla.privacy':
          'Your location stays on this device and is not sent out.',
      'tracker.title': 'Prayer Tracker',
      'tracker.completed': '{completed} / {total} completed',
      'tracker.privacy': 'Tracking data is stored only on this device using the selected day’s local date.',
      'premium.freeTitle': 'Core worship features are free.',
      'premium.freeFeatures': 'Free: prayer times, Qibla, basic notifications, Hijri calendar, daily content, basic tracking, tasbih, basic widget and the default mosque scene.',
      'premium.features': 'Premium: additional scene and widget styles, appearance customization and advanced on-device statistics.',
      'premium.loading': 'Loading store products…',
      'premium.unavailable': 'Store products are currently unavailable, so no price is shown. Free features remain available.',
      'premium.restore': 'Restore purchases',
      'premium.restoreSent': 'The restore request was sent to the store.',
      'premium.active': 'Premium active',
      'premium.cache': 'Store status is displayed using a local UX cache.',
      'notifications.description': 'We can calculate prayer times on your device and send local notifications.',
      'notifications.sound': 'Notification sound',
      'notifications.defaultSound': 'Default',
      'notifications.bundledSound': 'Bundled sound (when supported)',
      'notifications.silent': 'Silent',
      'notifications.friday': 'Friday reminder',
      'notifications.suhoor': 'Ramadan suhoor/Fajr reminder',
      'notifications.iftar': 'Ramadan iftar/Maghrib reminder',
      'notifications.permissionDone': 'Permission status processed',
      'notifications.managePermission': 'Manage notification permissions',
      'notifications.notice': 'Notifications are scheduled locally. A full-length adhan cannot be guaranteed in the background on every platform.',
      'notifications.permissionTitle': 'Local notification permission',
      'notifications.notNow': 'Not now',
      'notifications.continue': 'Continue',
      'notifications.advance': 'Remind in advance',
      'notifications.none': 'None',
      'notifications.minutes': '{minutes} minutes',
      'notifications.granted': 'Notification permission granted.',
      'notifications.denied': 'Notification permission denied.',
      'notifications.permanentlyDenied':
          'Notification permission must be enabled in Settings.',
      'notifications.unknown': 'Notification permission status is unknown.',
      'privacy.body': 'Prayer times and location use stay on the device. Prayer tracking, tasbih, favorites and notification schedules are stored locally. Widget data is shared only with the operating-system extension. Purchases use Apple or Google store infrastructure. There is no custom backend, ad tracking or analytics.',
      'privacy.delete': 'Delete all local data',
      'privacy.deleteTitle': 'Delete all local data?',
      'privacy.deleteBody': 'Settings, tracking history, tasbih state, favorites, notification preferences and widget data will be deleted. Bundled religious content is preserved.',
      'privacy.cancel': 'Cancel',
      'privacy.confirm': 'Delete',
      'privacy.deleted': 'Local data deleted. Safe defaults will be used.',
      'about.version': 'Version 1.0.0',
      'about.prayer': 'Prayer times are produced with offline on-device calculations. Hijri dates use a tabular calculation and may differ from local moon sightings and official announcements.',
      'about.content': 'Daily verse, hadith and prayer content uses bundled source metadata. Purchases are processed through Apple App Store or Google Play infrastructure.',
      'about.diyanet': 'The Diyanet question flow opens the official external service in a browser. This app is not Diyanet and does not issue religious rulings.',
      'placeholder': 'The {title} foundation screen is ready; its full feature will be added next.',
      'ramadan.suhoor':
          'Suhoor ends: {time} · Fajr under the selected calculation method',
      'ramadan.iftarRemaining': '{hours} hr {minutes} min until iftar · {time}',
      'ramadan.iftar': 'Iftar time: {time}',
    },
    'ar': {
      'appTitle': 'ديني',
      'nav.home': 'الرئيسية',
      'nav.quran': 'القرآن',
      'nav.worship': 'العبادة',
      'nav.calendar': 'التقويم',
      'nav.settings': 'الإعدادات',
      'home.greeting': 'يومك مفعم بالسكينة',
      'home.selectedLocation': 'الموقع المحدد',
      'home.nextPrayer': 'الصلاة القادمة',
      'home.remaining': 'متبقي {hours} س {minutes} د',
      'home.hijri': 'هجري {date}',
      'home.friday': 'الجمعة',
      'home.ramadan': 'رمضان',
      'home.qibla': 'القبلة',
      'home.tasbih': 'التسبيح',
      'home.tracker': 'متابعة الصلاة',
      'home.calendar': 'التقويم',
      'home.todayTimes': 'مواقيت اليوم',
      'home.now': 'الآن',
      'home.next': 'القادمة',
      'home.sunrise': 'الشروق · ليس وقت صلاة',
      'home.verse': 'آية اليوم',
      'home.hadith': 'حديث اليوم',
      'home.prayer': 'دعاء اليوم',
      'settings.title': 'الإعدادات',
      'settings.loadError':
          'تعذر تحميل الإعدادات. يمكن استخدام الإعدادات الآمنة الافتراضية.',
      'settings.calculation': 'طريقة الحساب',
      'settings.asrMethod': 'طريقة حساب العصر',
      'settings.clock24': 'نظام 24 ساعة',
      'settings.theme': 'المظهر',
      'settings.language': 'لغة التطبيق',
      'settings.languageHint': 'يتم تغيير اللغة فورًا.',
      'settings.hijriNotice': 'يعرض التاريخ الهجري بحساب جدولي دون اتصال، وقد يختلف يومًا واحدًا حسب رؤية الهلال والإعلانات الرسمية.',
      'settings.widgetLocation': 'إظهار اسم الموقع في الأداة',
      'settings.widgetLocationHint':
          'عند إيقافه تظهر مواقيت الصلاة دون مشاركة اسم المدينة.',
      'settings.widgetLoading': 'جارٍ تحميل إعداد خصوصية الأداة…',
      'settings.widgetDefault': 'إخفاء الموقع في الأداة هو الإعداد الافتراضي.',
      'settings.notifications': 'الإشعارات',
      'settings.askDiyanet': 'اسأل رئاسة الشؤون الدينية',
      'settings.about': 'حول التطبيق والمصادر',
      'settings.premium': 'المميز',
      'settings.privacy': 'مركز الخصوصية',
      'language.tr': 'Türkçe',
      'language.en': 'English',
      'language.ar': 'العربية',
      'prayer.fajr': 'الفجر',
      'prayer.sunrise': 'الشروق',
      'prayer.dhuhr': 'الظهر',
      'prayer.asr': 'العصر',
      'prayer.maghrib': 'المغرب',
      'prayer.isha': 'العشاء',
      'month.1': 'يناير',
      'month.2': 'فبراير',
      'month.3': 'مارس',
      'month.4': 'أبريل',
      'month.5': 'مايو',
      'month.6': 'يونيو',
      'month.7': 'يوليو',
      'month.8': 'أغسطس',
      'month.9': 'سبتمبر',
      'month.10': 'أكتوبر',
      'month.11': 'نوفمبر',
      'month.12': 'ديسمبر',
      'calendar.disclaimer': 'يعرض التاريخ الهجري بحساب جدولي دون اتصال، وقد تختلف التواريخ المرصودة حسب المنطقة والجهة الرسمية.',
      'calendar.previousMonth': 'الشهر السابق',
      'calendar.nextMonth': 'الشهر التالي',
      'calendar.today': 'اليوم',
      'calendar.religiousDay': 'مناسبة دينية',
      'calendar.selectedDay': 'اليوم المحدد',
      'calendar.noEvent': 'لا توجد مناسبة دينية مسجلة لهذا اليوم.',
      'calendar.dateNotice': 'هذه تواريخ محسوبة وفق التقويم الإسلامي وقد تختلف عن الإعلانات المحلية.',
      'weekday.1': 'ن',
      'weekday.2': 'ث',
      'weekday.3': 'ر',
      'weekday.4': 'خ',
      'weekday.5': 'ج',
      'weekday.6': 'س',
      'weekday.7': 'ح',
      'event.ramadan-start': 'بداية رمضان',
      'event.laylat-al-qadr': 'ليلة القدر',
      'event.eid-al-fitr': 'عيد الفطر',
      'event.eid-al-adha': 'عيد الأضحى',
      'event.mawlid': 'المولد النبوي',
      'event.miraj': 'ليلة الإسراء والمعراج',
      'event.berat': 'ليلة النصف من شعبان',
      'content.removeFavorite': 'إزالة من المفضلة',
      'content.addFavorite': 'إضافة إلى المفضلة',
      'content.collapse': 'عرض أقل',
      'content.more': 'قراءة المزيد',
      'content.copy': 'نسخ النص',
      'content.copied': 'تم نسخ النص',
      'content.share': 'مشاركة',
      'tasbih.select': 'اختر الذكر',
      'tasbih.target': 'الهدف',
      'tasbih.decrease': 'إنقاص واحد',
      'tasbih.increase': 'زيادة واحد',
      'tasbih.reset': 'إعادة الضبط',
      'tasbih.haptic': 'اهتزاز خفيف',
      'tasbih.history': 'الجلسات الأخيرة',
      'dhikr.subhanallah': 'سبحان الله',
      'dhikr.alhamdulillah': 'الحمد لله',
      'dhikr.allahu-akbar': 'الله أكبر',
      'dhikr.salawat': 'الصلاة على النبي',
      'qibla.sensorUnavailable': 'مستشعر البوصلة غير متاح. أمسك الهاتف بشكل مستوٍ وجرّب حركة المعايرة.',
      'qibla.heading': 'اتجاه الجهاز: {degrees}°{aligned}',
      'qibla.aligned': ' · بمحاذاة القبلة',
      'qibla.privacy': 'يبقى موقعك على هذا الجهاز ولا يتم إرساله.',
      'tracker.title': 'متابعة الصلاة',
      'tracker.completed': 'تم إكمال {completed} من {total}',
      'tracker.privacy': 'تُحفظ بيانات المتابعة على هذا الجهاز فقط وفق التاريخ المحلي لليوم المحدد.',
      'premium.freeTitle': 'ميزات العبادة الأساسية مجانية.',
      'premium.freeFeatures': 'مجانًا: مواقيت الصلاة والقبلة والإشعارات الأساسية والتقويم الهجري والمحتوى اليومي والمتابعة الأساسية والتسبيح والأداة الأساسية ومشهد المسجد الافتراضي.',
      'premium.features': 'المميز: مشاهد وأشكال إضافية للأداة وتخصيص المظهر وإحصاءات محلية متقدمة.',
      'premium.loading': 'جارٍ تحميل منتجات المتجر…',
      'premium.unavailable': 'منتجات المتجر غير متاحة حاليًا، لذلك لا يظهر السعر. تبقى الميزات المجانية متاحة.',
      'premium.restore': 'استعادة المشتريات',
      'premium.restoreSent': 'تم إرسال طلب الاستعادة إلى المتجر.',
      'premium.active': 'الاشتراك المميز نشط',
      'premium.cache': 'تُعرض حالة المتجر باستخدام ذاكرة محلية مؤقتة.',
      'notifications.description':
          'يمكننا حساب مواقيت الصلاة على جهازك وإرسال إشعارات محلية.',
      'notifications.sound': 'صوت الإشعار',
      'notifications.defaultSound': 'الافتراضي',
      'notifications.bundledSound': 'صوت مضمّن عند دعم المنصة',
      'notifications.silent': 'صامت',
      'notifications.friday': 'تذكير الجمعة',
      'notifications.suhoor': 'تذكير سحور رمضان والفجر',
      'notifications.iftar': 'تذكير إفطار رمضان والمغرب',
      'notifications.permissionDone': 'تمت معالجة حالة الإذن',
      'notifications.managePermission': 'إدارة أذونات الإشعارات',
      'notifications.notice': 'تُجدول الإشعارات محليًا. لا يمكن ضمان تشغيل الأذان كاملًا في الخلفية على جميع المنصات.',
      'notifications.permissionTitle': 'إذن الإشعارات المحلية',
      'notifications.notNow': 'ليس الآن',
      'notifications.continue': 'متابعة',
      'notifications.advance': 'التذكير مسبقًا',
      'notifications.none': 'بدون',
      'notifications.minutes': '{minutes} دقائق',
      'notifications.granted': 'تم منح إذن الإشعارات.',
      'notifications.denied': 'لم يتم منح إذن الإشعارات.',
      'notifications.permanentlyDenied':
          'يجب تفعيل إذن الإشعارات من الإعدادات.',
      'notifications.unknown': 'حالة إذن الإشعارات غير معروفة.',
      'privacy.body': 'تبقى مواقيت الصلاة واستخدام الموقع على الجهاز. تُحفظ متابعة الصلاة والتسبيح والمفضلة وجدولة الإشعارات محليًا. لا تُشارك بيانات الأداة إلا مع امتداد نظام التشغيل. تتم المشتريات عبر بنية متجر Apple أو Google. لا توجد خوادم خاصة أو تحليلات أو تتبع إعلاني.',
      'privacy.delete': 'حذف جميع البيانات المحلية',
      'privacy.deleteTitle': 'هل تريد حذف جميع البيانات المحلية؟',
      'privacy.deleteBody': 'ستُحذف الإعدادات وسجل المتابعة وحالة التسبيح والمفضلة وتفضيلات الإشعارات وبيانات الأداة. سيُحفظ المحتوى الديني المضمّن.',
      'privacy.cancel': 'إلغاء',
      'privacy.confirm': 'حذف',
      'privacy.deleted':
          'تم حذف البيانات المحلية. ستُستخدم الإعدادات الآمنة الافتراضية.',
      'about.version': 'الإصدار 1.0.0',
      'about.prayer': 'تُحسب مواقيت الصلاة محليًا دون اتصال. يستخدم التاريخ الهجري حسابًا جدوليًا وقد يختلف عن رؤية الهلال والإعلانات الرسمية.',
      'about.content': 'يستخدم محتوى الآية والحديث والدعاء اليومي بيانات المصادر المضمّنة. تتم المشتريات عبر Apple App Store أو Google Play.',
      'about.diyanet': 'يفتح مسار سؤال رئاسة الشؤون الدينية الخدمة الرسمية الخارجية في المتصفح. هذا التطبيق ليس تابعًا للرئاسة ولا يصدر أحكامًا دينية.',
      'placeholder':
          'شاشة {title} الأساسية جاهزة؛ ستُضاف الوظيفة الكاملة لاحقًا.',
      'ramadan.suhoor':
          'نهاية السحور: {time} · وقت الفجر وفق طريقة الحساب المحددة',
      'ramadan.iftarRemaining': 'متبقي للإفطار {hours} س {minutes} د · {time}',
      'ramadan.iftar': 'وقت الإفطار: {time}',
    },
  };
}

extension AppLocalizationsContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
